### ISSUE TITLE
/match - POST should return all match data

### ISSUE THREAD

**Issue by richlaconte** [StepowskiEric/Overwatchstats#14]
Currently, most routes return `data=data` for the requests. This isn't a great practice, because we're just sending back the request data rather than verified data from the back-end.

Ideally, when someone creates a new match, the POST will get called and a new match is added to the DB. However, in order for the frontend to know there is a new match in the DB it will have to do a /match GET request for the new data.

Instead of the above example, we can have the POST request respond with the new match data for the user. (every match item associated with the given user) This way the POST serves both to add the match and give the frontend updated data, rather than making two calls one after the other to the backend.

**Comment by richlaconte** [comment]
We'll want an array of all the matches associated with the given user.

**Comment by StepowskiEric** [comment]
Closing this as we completed it together. Thanks for the help!
