### ISSUE TITLE
Login needs to check for correct password

### ISSUE THREAD

**Issue by richlaconte** [StepowskiEric/Overwatchstats#2]
Login route should find the user with given email address(already happening), but then needs to check the provided password with the one on the user account found of given email.

If the password doesn't match send back an error message letting the user know.

Should also send back an error message if the email isn't found as an existing user.

**Comment by richlaconte** [comment]
Also needs to send back user data (like /register) if the email+password match.

**Comment by StepowskiEric** [comment]
Closed as the newest version fixed this.
