### ISSUE TITLE
/addMatch route

### ISSUE THREAD

**Issue by richlaconte** [StepowskiEric/Overwatchstats#3]
Should add to the 'matches' array of 'match' objects on the user's account object

a match should look something like this in my opinion:
```
{
    id: 0,
    map: 'volskaya',
    outcome: 0,
    players: [
        {
            name: 'dichi'
        },
        {
            name: 'jerry'
        }
    ],
    datetime: dateTime()
}

```
id - int - this can just be matches.length() at the time of the creation of the match.
map - string of the map name
outcome - int, 0/1/2 = loss/win/draw
players - array/list of players class (I can't think of any other important fields other than name)
datetime - dateTime object of when the match was added (when this route/function was used) so something like dateTime.now()

**Comment by richlaconte** [comment]
Update - for the players class
I think it should be something like:

```
{
    name: 'name',
    role: 'tank',
    heroes: [
        'roadhog',
        'zarya'
    ]
}
```
name - string
role - string
heroes - array of strings

**Comment by richlaconte** [comment]
Route should return array of matches if the add was successful

**Comment by StepowskiEric** [comment]
Added routes.
