### ISSUE TITLE
Route bugs

### ISSUE THREAD

**Issue by StepowskiEric** [StepowskiEric/Overwatchstats#4]
Need to troubleshoot and add a ton of error handling based on what the user puts into the forms.

player route needs to check if the username is found and if not post a json response and the same with add match route.

**Comment by richlaconte** [comment]
FOR ALL OF THESE ROUTES - need JWT auth before working

Login:
- [x] GET - looks for JWT auth, and replies with user data

Logout:
- [x] POST - void JWT

Player:
- [x] needs a GET route - return all players attached to given user
- [x] DB - have username on player reference user and vice versa
- [x] UPDATE - change the player data
- [x] Delete player route (use DELETE verb) - removes the player from the user

(REWORK - match)
Match:
- [x] GET - return all matches on user account
- [x] POST - add new match (already exists, just change route name)
- [x] UPDATE - change the match data
- [x] DELETE - remove match from user

**Comment by StepowskiEric** [comment]
NOTE ** new unique table with a secondary table for other rows...

**Comment by richlaconte** [comment]
PLAYER UPDATES:
- [ ] role and heroes shouldn't be required to create/add a player (in POST)

**Comment by richlaconte** [comment]
MATCH ROUTE CHANGES:
Match should have a 'players' key that is an array of players, but each player also has a 'role' and 'heroes' designated for this particular match.

**Comment by richlaconte** [comment]
Addressed in 944923e589a59f76ed64cc0cf365006db550bc9f
